application: united-column-581
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/stylesheets

- url: /js
  static_dir: static/js

- url: /.*
  script: blargh.application 

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
